2021-04-16 15:18:59,442 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:52]
2021-04-16 15:20:35,474 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:52]
2021-04-16 15:55:18,294 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:52]
2021-04-16 16:34:50,077 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:57]
2021-04-16 17:36:38,803 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:57]
2021-04-16 17:37:17,964 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:57]
2021-04-16 17:39:15,561 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:57]
2021-04-19 17:00:39,685 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:57]
2021-04-19 17:01:31,009 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:57]
2021-04-19 17:01:42,400 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:57]
2021-04-19 17:12:23,581 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:57]
2021-04-19 17:15:04,509 ERROR: Exception on /reset_password_request [POST] [in /home/dholland/dev/microblog/venv/lib64/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/dholland/dev/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dholland/dev/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dholland/dev/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dholland/dev/microblog/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dholland/dev/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dholland/dev/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dholland/dev/microblog/app/routes.py", line 172, in reset_password_request
    send_password_reset_email(user)
  File "/home/dholland/dev/microblog/app/email.py", line 12, in send_password_reset_email
    token = user.get_reset_password_token()
AttributeError: 'User' object has no attribute 'get_reset_password_token'
2021-04-19 17:19:10,671 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:57]
2021-04-19 17:19:24,330 ERROR: Exception on /reset_password_request [POST] [in /home/dholland/dev/microblog/venv/lib64/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/dholland/dev/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dholland/dev/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dholland/dev/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dholland/dev/microblog/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dholland/dev/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dholland/dev/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dholland/dev/microblog/app/routes.py", line 172, in reset_password_request
    send_password_reset_email(user)
  File "/home/dholland/dev/microblog/app/email.py", line 12, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/dholland/dev/microblog/app/models.py", line 62, in get_reset_password_token
    return jwt.encode({'reset_password':self.id, 'exp':time()+expires_in}, app.config['SECRET_KEY'], algorithm='HS256')
NameError: name 'jwt' is not defined
2021-04-19 17:20:31,849 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:57]
2021-04-19 17:34:50,925 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:57]
2021-04-19 17:39:24,540 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:57]
2021-04-19 18:02:33,243 INFO: Microblog startup [in /home/dholland/dev/microblog/app/__init__.py:57]
